services:
  plant_ai_back:
    image: plant-ai-back:latest
    ports:
      - "8080:8080"
    secrets:
      - AuthDbConnectionString
      - SecretKey
  db:
    image: plant-ai-auth:latest
    ports:
      - "5432:5432"
secrets:
  SecretKey:
    external: true
  AuthDbConnectionString:
    external: true
