services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/DbPassword
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    secrets:
      - DbPassword
  # auth:
  #   image: auth:latest
  #   ports:
  #     - "8082:8080"
  #   depends_on:
  #     - db
  #   secrets:
  #     - AuthDbConnectionString
  #     - SecretKey
  #     - DbPassword
  broker:
    image: broker:latest
    ports:
      - "1883:1883"

  main:
    image: main:latest
    ports:
      - "8080:8080"
    secrets:
      - DbPassword
      - PlantAIDbConnectionString

  worker:
    image: worker:latest
    ports:
      - "50051:50051"

  telemetry:
    image: telemetry:latest
    ports:
      - "8081:8080"
    depends_on:
      - db
    secrets:
      - DbPassword
      - TelemetryDbConnectionString

  front:
    image: front:latest
    ports:
      - "443:443"
    depends_on:
      - main
      - telemetry

secrets:
  SecretKey:
    external: true
  DbPassword:
    external: true
  AuthDbConnectionString:
    external: true
  TelemetryDbConnectionString:
    external: true
  PlantAIDbConnectionString:
    external: true
