// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelemetryService.Infrastructure.Persistant;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260606192723_add link2")]
    partial class addlink2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.DataGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GroupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MqttClientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MqttClientId");

                    b.ToTable("DataGroups");
                });

            modelBuilder.Entity("Core.Models.SensorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("SensorTypeId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SensorTypeId");

                    b.ToTable("SensorsData");
                });

            modelBuilder.Entity("Core.Models.SensorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SensorType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeName = "Temperature"
                        },
                        new
                        {
                            Id = 2,
                            TypeName = "Humidity"
                        });
                });

            modelBuilder.Entity("Core.Models.mqtt.BrokerParpameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Port")
                        .IsUnique();

                    b.ToTable("BrokerParameters");
                });

            modelBuilder.Entity("Core.Models.mqtt.MqttClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastMessageDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.ToTable("MqttClients");
                });

            modelBuilder.Entity("Core.Models.mqtt.TopicDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Topic")
                        .IsUnique();

                    b.ToTable("TopicDefinitions");
                });

            modelBuilder.Entity("MqttClientTopicDefinition", b =>
                {
                    b.Property<int>("SubscriptionsId")
                        .HasColumnType("integer");

                    b.Property<int>("TopicsId")
                        .HasColumnType("integer");

                    b.HasKey("SubscriptionsId", "TopicsId");

                    b.HasIndex("TopicsId");

                    b.ToTable("MqttClientTopicDefinition");
                });

            modelBuilder.Entity("Core.Models.DataGroup", b =>
                {
                    b.HasOne("Core.Models.mqtt.MqttClient", "MqttClient")
                        .WithMany("DataGroups")
                        .HasForeignKey("MqttClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MqttClient");
                });

            modelBuilder.Entity("Core.Models.SensorData", b =>
                {
                    b.HasOne("Core.Models.DataGroup", "DataGroup")
                        .WithMany("SensorsData")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.SensorType", "SensorType")
                        .WithMany("SensorsData")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataGroup");

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("Core.Models.mqtt.MqttClient", b =>
                {
                    b.HasOne("Core.Models.mqtt.BrokerParpameters", "Broker")
                        .WithMany("Clients")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("MqttClientTopicDefinition", b =>
                {
                    b.HasOne("Core.Models.mqtt.MqttClient", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.mqtt.TopicDefinition", null)
                        .WithMany()
                        .HasForeignKey("TopicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Models.DataGroup", b =>
                {
                    b.Navigation("SensorsData");
                });

            modelBuilder.Entity("Core.Models.SensorType", b =>
                {
                    b.Navigation("SensorsData");
                });

            modelBuilder.Entity("Core.Models.mqtt.BrokerParpameters", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Core.Models.mqtt.MqttClient", b =>
                {
                    b.Navigation("DataGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
