// <auto-generated />
using System;
using Infrastructure.Persistant;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PlantAIDbContext))]
    [Migration("20260623000103_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.ControlElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ControlElement");
                });

            modelBuilder.Entity("Core.Models.Fnn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ControlId")
                        .HasColumnType("integer");

                    b.Property<string>("ParamsAddr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ControlId")
                        .IsUnique();

                    b.ToTable("Fnn");
                });

            modelBuilder.Entity("Core.Models.FnnAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Answer")
                        .HasColumnType("integer");

                    b.Property<int>("DataGroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FnnId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FnnId");

                    b.ToTable("FnnAnswer");
                });

            modelBuilder.Entity("Core.Models.Fnn", b =>
                {
                    b.HasOne("Core.Models.ControlElement", "ControlElement")
                        .WithOne("Fnn")
                        .HasForeignKey("Core.Models.Fnn", "ControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ControlElement");
                });

            modelBuilder.Entity("Core.Models.FnnAnswer", b =>
                {
                    b.HasOne("Core.Models.Fnn", "Fnn")
                        .WithMany("FnnAnswers")
                        .HasForeignKey("FnnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fnn");
                });

            modelBuilder.Entity("Core.Models.ControlElement", b =>
                {
                    b.Navigation("Fnn")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Models.Fnn", b =>
                {
                    b.Navigation("FnnAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
